apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
        app: app1
spec:
  replicas: 3  # Specify the desired number of replicas
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: aem7586735.azurecr.io/app1:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: default
  labels:
    app: app1
 
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app1
  type: LoadBalancer
